### ISSUE TITLE
invalid_blocks response with no error message

### ISSUE THREAD

**Issue by bruuuuuuuce** [slackapi/java-slack-sdk#1017]
We are sometimes getting a 400 `invalid_blocks` back from the slack api when using the java slack sdk, trying to post a message to our webhook. Most of the time its working fine, but we are having trouble debugging this error. There is no error message, and no transaction id associated with the request. I have reached out to the slack support team, who told me to raise an issue here. What is the best way to debug this? Ideally I would like to be able to run some validation against our blocks to tell us what is making them invalid. 

Thanks!

**Comment by seratch** [comment]
Hi @bruuuuuuuce, thanks for writing in! Unfortunately, the uninformative error response is not due to this Java SDK but the server-side behavior.

I would suggest either of the following to figure the cause out:
* Enable debug-level logging, get the raw JSON data of blocks, and past it in [Block Kit Builder](https://app.slack.com/block-kit-builder) to see the errors
* Switch to [chat.postMessage API](https://slack.dev/java-slack-sdk/guides/composing-messages) with a token

When you use chat.postMessage API to post a message, you will receive more information in its response. The API's response includes a more detailed error like this:
```json
{
  "ok": false,
  "error": "invalid_blocks",
  "errors": [
    "must define either `text` or `fields` [json-pointer:/blocks/0/type]"
  ],
  "response_metadata": {
    "messages": [
      "[ERROR] must define either `text` or `fields` [json-pointer:/blocks/0/type]"
    ]
  }
}
```
You can see the same error in Block Kit Builder too.

I hope this helps.

**Comment by bruuuuuuuce** [comment]
Thanks, I have enabled debug logging on my service, will get back to you on the error that we are seeing

**Comment by bruuuuuuuce** [comment]
The error that I was seeing was related to having a title while also adding blocks to my request. So I changed
```
val payload = Payload.builder().blocks(blocksToUse).text(title).build()
```
to
```
val payload = Payload.builder().blocks(blocksToUse).build()
```

Which fixed my problem
