### ISSUE TITLE
Question about RTM.start vs rtm.connect

### ISSUE THREAD

**Issue by RajeevLochan82** [slackapi/java-slack-sdk#1066]
We have a java application which listen to slack channels and post appropriate response. After receiving the email about depreciation of rtm.start function, I modified our slack application to use rtm.connect function. By making this change our application was working fine and I did not have to make any additional code changes. But starting 9/27 evening our application stopped working. It looks like the response provided by connect is completely different than start function. As our application was working fine, so I did not looked further in our code for any additional changes.

It looks like our application was parsing following additional data from rtm.start() JSON response. Can you please provide me a sample of old rtm.start() function and also suggest what alternative APIs we will need to use together with rtm.connect() function to get the following data?

Users
Members
Bots
Channels
Groups
Ims
Self
Team
url

**Comment by RajeevLochan82** [comment]
Hello,

Can I get sample payload of old rtm.start() function ?

**Comment by seratch** [comment]
Checking this migration guide may be helpful too: https://api.slack.com/changelog/2021-10-rtm-start-to-stop#how__looking-for-conversations-users-preferences-and-plans

**Comment by RajeevLochan82** [comment]
Any limitations if we choose to develop this slack application in .Net vs Java ? Most of the example code seem to be provided in Java, so wondering if there are any limitations if we try to develop this slack application in .Net.

**Comment by WilliamBergamin** [comment]
We unfortunately do not officially support `.Net` if you want to use it you would have to use a [third party open sourced library](https://api.slack.com/community). I am unable to comment on the developer experience since I've never used `.Net`.

We develop and support the [Bolt family of frameworks](https://api.slack.com/tools/bolt) along with the [SDKs](https://api.slack.com/start/building#sdks) found in the [slackapi org](https://github.com/slackapi), we also create and maintain [sample projects](https://github.com/slack-samples) that use theses frameworks and SDK's
