### ISSUE TITLE
"access_denied" errors in the OAuth callback

### ISSUE THREAD

**Issue by gh-gonzo** [slackapi/java-slack-sdk#1075]
My app uses Bolt for Java with Spring Boot. Sometimes in my production server logs I see an error like this:

`
c.s.a.b.s.b.o.d.OAuthDefaultErrorHandler : Received error code in OAuth callback: VerificationCodePayload(code=null, state=514b0050-e97b-417c-9b0c-8ffe9a936aa0, error=access_denied, nonce=null)
`

I wonder what the reason is?

**Comment by seratch** [comment]
Hi @gh-gonzo, thanks for asking the question! The error code can be returned when an installing user click "Cancel" in the OAuth confirmation page. So, it is a possible normal pattern.

<img src="https://user-images.githubusercontent.com/19658/197905358-a0a0fb46-50e8-4395-a689-542de3775921.png" width=400 />

Let me know if you have any follow-up comments. Otherwise, we will close this issue soon.

**Comment by gh-gonzo** [comment]
Yeah, just checked and that's it. Thank you for quick response 🙏
