### ISSUE TITLE
FilesUploadV2Request: markdown format for initialComment does not work unlike v1

### ISSUE THREAD

**Issue by plshapkin** [slackapi/java-slack-sdk#1121]
#### The Slack SDK version

1.27.3

#### Java Runtime version

OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)

#### OS info

ProductName:		macOS
ProductVersion:		13.1
BuildVersion:		22C65
Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000

#### Steps to reproduce:

1. Add link like `<https://example.com|example.com>` in `FilesUploadV2RequestBuilder.initialComment()`
2. Build `FilesUploadV2Request`
3. Send request via `MethodsClient.filesUploadV2()`

#### Expected result:

Link parsed like [example.com](https://example.com)

#### Actual result:

Link not parsed, displayed plain text `<https://example.com|example.com> `

**Comment by seratch** [comment]
Hi @plshapkin, thanks for writing in!

Unfortunately, the lack of markdown format support is a known issue and we don't have any updates since the issue was initially reported. We cannot tell when and whether this can be improved in the future. See the similar ones:
* https://github.com/slackapi/python-slack-sdk/issues/1289
* https://github.com/slackapi/node-slack-sdk/issues/1561

The only workaround that I can suggest is to use chat.postMessage with files' permalink URLs: https://github.com/slackapi/python-slack-sdk/issues/1194#issuecomment-1076962918

I know this is not a great answer but I hope this was helpful to you.

**Comment by seratch** [comment]
Hi! Thank you very much for your patience regarding this issue. The server-side has recently been enhanced, so now the API accepts mrkdwn format for the initial_comment parameter! Let me close this issue now 🙇
