### ISSUE TITLE
Is it possible to get a valid trigger_id in test ?

### ISSUE THREAD

**Issue by smallufo** [slackapi/java-slack-sdk#1170]
bolt 1.29.2

I want to test my view design , want to see how it works in my private channel  
I hope I can test it locally , but found it seems impossible
```

val birthdayFormTemplate = """
        {
            // skipped json content
        }
    """.trimIndent()

slackApp.slack.methods().viewsOpen { b ->
        b.token(slackApp.config().singleTeamBotToken)
            .triggerId(triggerId) // <-- unable to get a valid triggerId
            .viewAsString(birthdayFormTemplate)
    }

```
As there is no way to get a valid trigger_id . It seems it's only available at runtime, resides inside SlashCommandRequest... etc

Is there any solution to solve this ?

Thanks.

**Comment by seratch** [comment]
Hi @smallufo, thanks for writing in! 

Since a trigger_id must be associated with a user action inside Slack, there is no way to generate a valid value without real user interactions. 

To verify your blocks in a modal, you can use Block Kit Builder (https://app.slack.com/block-kit-builder) instead. You cannot pass your Java code to the tool but I believe it's not so bad to start with raw JSON data in Block Kit Builder first and then convert it to Java code afterward.

I hope this helps.

**Comment by smallufo** [comment]
thanks
