### ISSUE TITLE
for slash command, do we need to expose api to public?

### ISSUE THREAD

**Issue by mallik30** [slackapi/java-slack-sdk#1183]
I built a couple of slash commands with internal URLs which work only in my company’s network.
in order to make it work do we need to expose the API to the public? 
if yes, are there any alternatives without exposing the URL to the public?
Kindly assist asap

**Comment by seratch** [comment]
Hi @mallik30, you can try Socket Mode for it:
* https://slack.dev/java-slack-sdk/guides/getting-started-with-bolt-socket-mode
* https://slack.dev/java-slack-sdk/guides/socket-mode

**Comment by mallik30** [comment]
@seratch can you please provide sample app in java

**Comment by mallik30** [comment]
@seratch created the token by following doc, but it is failing with the following error in https://api.slack.com/methods/auth.test/test

```
{
    "ok": false,
    "error": "invalid_auth"
}
```

**Comment by seratch** [comment]
@mallik30 When you run a Socket Mode app, any web app development frameworks such as Spring Boot are not necessary but you may need to run apps using Spring Boot for some reason. In that case, these examples may be helpful:

* https://github.com/slackapi/java-slack-sdk/issues/1044#issuecomment-1243406113
* https://github.com/slackapi/java-slack-sdk/issues/1114#issuecomment-1413138877

The "invalid_auth" error should be caused by your misconfiguration. Usually the error can be raised when you pass an invalid token string when initializing an app.

I hope this helps. If you don't have any further questions, would you mind closing this issue?

**Comment by mallik30** [comment]
@seratch I got invalid_auth in slack UI in the following link
https://api.slack.com/methods/auth.test/test

```
{
    "ok": false,
    "error": "invalid_auth"
}
```

**Comment by mallik30** [comment]
<img width="1043" alt="Screenshot 2023-07-16 at 1 08 57 AM" src="https://github.com/slackapi/java-slack-sdk/assets/33911547/3aa4d335-1671-469f-86cc-824791bda612">

**Comment by mallik30** [comment]
I tested with 3 generated tokens, it's still returning invalid_auth

**Comment by seratch** [comment]
This is not an issue. The app-level token starting with the `xapp-` prefix is supposed to be used only for establishing a WebSocket connection for Socket Mode. The `auth.test` API or any other web API calls must be associated with bot/user tokens (xoxb-, xoxp-) in a certain Slack workspace.

When it comes to this Java SDK, you can use an app-level token (xapp-) to initialize a `SocketModeApp` instance, which manages WebSocket connections for you. To perform Slack's other web APIs such as chat.postMessage API, you still need to use either bot or user tokens. Does this make sense to you?

**Comment by mallik30** [comment]
please join for a quick sync up
https://us04web.zoom.us/j/2058737703?pwd=U2c2ekJ5RGFvYVprOWN5Vkw1MkFFQT09

**Comment by mallik30** [comment]
@seratch here's my code
https://github.com/mallik30/bot-socketmode/blob/main/src/main/java/com/arjun/slack/api/SocketModeManager.java

**Comment by mallik30** [comment]
I got it working using your second example, thank you
https://github.com/slackapi/java-slack-sdk/issues/1114#issuecomment-1413138877
