### ISSUE TITLE
chat.postMessage - icon_url not working.

### ISSUE THREAD

**Issue by cprashantgupta** [slackapi/java-slack-sdk#1197]
We are posting message from our BOT with customize username and icon_url. 

When customizing icon_url it works for one but not other 
- WORKING URL - https://marvin-assets.s3.eu-west-2.amazonaws.com/Marvinlogoless.png
- **NOT WORKING URL - https://api.dev.sharewithmarvin.io/avatar/pub/api/v1/avatar/64dfc6c50ed89f4044196b14**

> Note we use custom username (not bot name) as argument to above call, so that it appears as of the user is sending this message. using permission **[chat:write.customize](https://api.slack.com/methods/chat.postMessage#authorship)**

### Reproducible in:
```
<dependency>
      <groupId>com.slack.api</groupId>
      <artifactId>bolt-micronaut</artifactId>
      <version>1.30.0</version>
 </dependency>
```

#### The Slack SDK version

(Paste the output of `mvn dependency:tree | grep com.slack.api` or `gradle dependencies | grep com.slack.api`)

#### Java Runtime version

Java 11

#### OS info
Ubuntu Latest

#### Steps to reproduce:

1.  Create request to do chat.postMessage 
2. Pass in icon_url as : https://api.dev.sharewithmarvin.io/avatar/pub/api/v1/avatar/64dfc6c50ed89f4044196b14 
3. It fails without giving any erorr/ warning.

#### Expected result:

icon_url should work.

#### Actual result:

(Tell what actually happened with logs, screenshots)

**Comment by seratch** [comment]
Hi @cprashantgupta,

Thank you for reaching out with your question. I've taken a look at the URLs you provided. It appears that the second URL isn't publicly accessible, which is why you're encountering issues when trying to use it in your Block Kit message. As with the first URL, it's required to use a publicly reachable URL for it to function correctly within Slack.

I understand this might be a constraint for your requirements, but as of now, we don't have immediate plans to allow private URLs. However, given the frequency of this feature request, we may consider potential enhancements to the platform in this regard. For any future updates or changes, please keep an eye on our changelog at https://api.slack.com/changelog.

At this time, I'll close out this issue. I hope this clarifies things for you, and thank you for engaging with our platform!

**Comment by cprashantgupta** [comment]
@seratch  : The second URl is also public, you should be able to open that URL right now. 

https://api.dev.sharewithmarvin.io/avatar/pub/api/v1/avatar/64dfc6c50ed89f4044196b14

**Comment by seratch** [comment]
@cprashantgupta Thanks for updating. I can now access the URL. However, I noticed a delay when loading the image for the first time. If there's a similar delay when using the icon_url in a Slack message, the Slack platform might not utilize the URL due to a fetch timeout. For consistent results, it's essential to ensure the image hosting service responds quickly and consistently.

**Comment by cprashantgupta** [comment]
@seratch  : Thank you for reply, can you please let me know the fetch timeout , after which Slack Platform timeout the request ?

**Comment by seratch** [comment]
Yes, you're right. The platform does not use external resource URLs without varifying if it's safe. So, icon_url needs to be public and responsible when posting a message with it via chat.postMessage API.
