### ISSUE TITLE
Request for Slack api WebhookResponse send(String url, Payload payload)  to return ts value

### ISSUE THREAD

**Issue by rhibiscusc** [slackapi/java-slack-sdk#1254]
My issue is similar to the problem described here: https://stackoverflow.com/questions/56291169/slack-get-thread-id-after-posting-message-using-incoming-web-hook

I am currently using slack as our new service notification hub. But I like to organize the notification per a specific event id. So when the service is going to persist the ts value for the first message related to the event id and put subsequent message in the thread.
 
### Category (place an `x` in each of the `[ ]`)

* [ x] **bolt** (Bolt for Java)
* [ ] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [ ] **slack-api-client** (Slack API Clients)
* [ ] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you agree to those rules.

**Comment by hello-ashleyintech** [comment]
Hi, @rhibiscusc! Thank you for your question! 🙌 

Based on [the documentation](https://api.slack.com/messaging/webhooks#threads), it looks like not returning the `ts` is not just a limitation of the Java SDK, but a limitation of Incoming Webhooks in general:
> You can use an Incoming Webhook to make your message appear as a reply in a thread. You'll need to retrieve the message ts value, however, as it is not returned when sending a request to an Incoming Webhook.

You can retrieve the `ts` value in one of the following ways:
* Enable and use the [Events](https://api.slack.com/events) API so that you can subscribe to event types that will send a callback when a new message is sent by your webhook.
* Use the [search.messages](https://api.slack.com/methods/search.messages) method to search for the message you sent based on the timestamp.
* Use the [conversations.history](https://api.slack.com/methods/conversations.history) method to search for the message from a set of messages.

I hope this helps!

**Comment by seratch** [comment]
As Ashly mentioned, you can utilize other web APIs to fetch the data. Another suggestio is to switch to chat.postMessage API rather than using an incoming webhook. The chat.postMessage API response provides the posted message's channel ID and ts. This should be the most straight-forward way to achieve your goal. 

Since we don't have anything else to share on this topic, let me close this issue. That said, whenever you have any follow up questions on this topic, please don't hesitate to write in!
