### ISSUE TITLE
SVG support for image block

### ISSUE THREAD

**Issue by sebastiannberg** [slackapi/java-slack-sdk#1329]
would like to be able to use SVG files directly in the image block when working with the Slack API and Bolt for Java. As SVG is a widely used format for images, supporting this format would enhance the flexibility and usability of the Slack API.

### Category

* [x] **bolt** (Bolt for Java)
* [x] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [x] **slack-api-client** (Slack API Clients)
* [ ] **slack-api-model** (Slack API Data Models)
* [x] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you agree to those rules.

**Comment by hello-ashleyintech** [comment]
Hi, @sebastiannberg! Thank you for submitting this! 🙇 

I attempted to upload an SVG to my Slack workspace and then tried to embed it in Block Kit to see if there was potentially a workaround, but this confirmed that SVGs are currently not supported as you mentioned.

If this was a feature supported by Block Kit, I imagine we could add or extend our SDKs to incorporate that compatibility pretty easily. Unfortunately, since it was confirmed that this is [not currently a feature supported by Block Kit](https://api.slack.com/reference/block-kit/blocks#image), I recommend emailing [feedback@slack.com](mailto:feedback@slack.com) with your request. Doing this will surface your request to the folks at Slack who make the Decisions, which could best influence the addition of the feature. 🙌

**Comment by sebastiannberg** [comment]
Hi @hello-ashleyintech,

Thank you for confirming the limitations regarding SVG support in Slack's Block Kit.

I will follow your suggestion and send a request to feedback@slack.com to bring this to the attention of Slack's decision-makers.

Thanks for your help.
