### ISSUE TITLE
Certain team ids getting 401 HTTP response from event subscription URL while others work

### ISSUE THREAD

**Issue by jshao-brex** [slackapi/java-slack-sdk#1334]
**Problem:**

Our Slack app uses "Event Subscriptions" with Slack JAVA SDK to listen to events triggered in the Slack app. While it works well for the majority of our customers, we got reports from some customers that the Slack app is not responsive for all of their users and showing the following error: 
<img width="238" alt="image" src="https://github.com/slackapi/java-slack-sdk/assets/105669221/a3b9dea2-7d0b-47eb-b60f-046eeccf2d47">

**Troubleshooting done so far**

Our logs show that our event subscription URL is **not** getting any events for these workspaces/Slack teams. 

We opened a help request. One Slack team member checked one of the impacted workspaces, and told us that Slack events for this workspace were sent, but all of them got a **401** HTTP response. 

We reviewed the Slack JAVA SDK source code and our own code. It seems like the only place that could return a 401 response is the [Request Verification](https://github.com/slackapi/java-slack-sdk/blob/main/bolt/src/main/java/com/slack/api/bolt/middleware/builtin/RequestVerification.java) middleware. So, we disabled the built-in Request verification middleware in our app config and created a custom middleware with the same logic but additional logging. However, we are not seeing any requests rejected and returning 401. 

We also considered the possibility that the request was rejected at the network level by ingress before it reached our application code. However, this seems not possible since it only and consistently happens to a subset of workspaces/team IDs. The component that rejected it has to understand the payload and know how to extract the team ID from it. Neither the network-level component nor ingress is checking the payload in the Slack event HTTP request...

Our Slack app is not using socket mode.

**Could you provide some guidance on the next step in troubleshooting this issue? Are there any other middleware/components that might reject the requests?**

#### The Slack SDK version

1.38.2

#### Java Runtime version

openjdk version "11.0.22" 2024-01-16

#### OS info

N/A

**Comment by misscoded** [comment]
Hi @jshao-brex! I spoke with @seratch, the creator and primary maintainer of this library, to get his thoughts on the issue you've described and to ensure we got you the best answer out the gate. 🙂 

One likely cause came to mind, which is **a token resolution issue occurring within the authorize function**. Code sites to do some additional debugging include [here](https://github.com/slackapi/java-slack-sdk/blob/9f8ff5108697492299ebeddcf39344c7f328331d/bolt/src/main/java/com/slack/api/bolt/middleware/builtin/MultiTeamsAuthorization.java#L232) and [here](https://github.com/slackapi/java-slack-sdk/blob/v1.40.2/bolt/src/main/java/com/slack/api/bolt/middleware/builtin/MultiTeamsAuthorization.java#L309). Though it could be something else, **one reason it might happen is due to a grid migration, where the app is still available in the original/migrated workspace, but the `enterprise_id`/`team_id` is no longer the same.**

To avoid this happening in the future, he recommended:

1. Periodically (ie, daily) running an `auth.test` API call for all stored tokens and update the metadata, as necessary (such as `team_id`)
2. Subscribe to grid migration events in the Events API and update the metadata in database once the migration has finished, when and if that occurs

We hope this is helpful. Let us know if this ends up being the cause of the issue you're seeing!

**Comment by jshao-brex** [comment]
Thank you both @misscoded and @seratch!! These are very helpful. We are looking at these and will let you know how it goes.
