### ISSUE TITLE
Uploaded .xlsx File Recognized as a Binary File When Using Apache POI 4.1.2 with Slack Java SDK

### ISSUE THREAD

**Issue by diiiiiiiino** [slackapi/java-slack-sdk#1353]
Hello,  
I am using the Slack Java SDK to send file links via Slack channel messages, but the uploaded `.xlsx` file is being recognized as a binary file, as shown in the image below.  
The file is generated in Java using Apache POI version 4.1.2. When generated with version 3.17, it is recognized as an Excel file. Could you help me understand what the issue might be that is causing the file to not be recognized properly?

#### The Slack SDK version
com.slack.api:slack-api-client:1.42.0

#### Java Runtime version
java 21

#### OS info
ProductName:		macOS
ProductVersion:		13.2.1

#### Expected result:
<img width="434" alt="스크린샷 2024-08-30 오후 2 39 17" src="https://github.com/user-attachments/assets/2ba51d89-975b-485b-a628-ed264e6ca22d">

#### Actual result:
<Img width="434" src="https://github.com/user-attachments/assets/659a896d-7585-4951-bee0-d06d0980d45b">

**Comment by seratch** [comment]
Hi @diiiiiiiino, thanks for asking the question.

We are unable to help you with Apache POI specific questions, but perhaps its new major version might generate different file metadata, which may not be recognized by Slack's auto file type detection.

As a workaround, explicitly passing the file type may help rather than relying on Slack's auto-detection. Please refer to https://github.com/slackapi/java-slack-sdk/issues/995 for details.

**Comment by diiiiiiiino** [comment]
Thank you for your response

**Comment by seratch** [comment]
Sorry, it seems that the parameter is no longer supported in the new way to upload files. Please try to set complete metadata to your generated Excel files (like the ones human manually crafts).
