### ISSUE TITLE
Bot Missed Multiple Events

### ISSUE THREAD

**Issue by abubakar364** [slackapi/java-slack-sdk#1354]
We are using SDK bot to consume events from slack. It works fine normally in Asian morning and start missing event after 5 PM PKT. I Communicated with slack team and they tell me that 

![image](https://github.com/user-attachments/assets/46561165-411d-41e6-abc4-17576765fe63)

can you please check this out.

**Comment by filmaj** [comment]
Sorry, there is nothing we can do on our end. The error points to network disconnect issues between wherever your app is running and Slack's backend. Unless you can provide debug-level logs from your app that point to a problem with logic in this framework, I am afraid we cannot do much to help.

**Comment by seratch** [comment]
I feel the same. It seems that this is not a bolt-java specific question. I am not sure why your app endpoint is down during a specific time, but one possible cause might be that your infrastructure has scheduled operations (e.g., terminating app instances/load balancers when your business hours end). I'd recommend checking your app/infra logs to figure out what's happening. We hope you'll figure out the cause soon.

**Comment by abubakar364** [comment]
It means that it's the problem of EKS network, right?

**Comment by filmaj** [comment]
> It means that it's the problem of EKS network, right?

It's possible, it all depends on the infrastructure your app is deployed to. Perhaps the container the app is running on is being recycled at this moment, or some other infrastructure setup issue or routine is causing a disconnect.

One other note: there is mention of socket-mode in the screenshot; if you are currently using socket mode for the app, if possible, consider moving to HTTP delivery of events rather than continuing to use socket mode. While socket mode is convenient while developing an application, it establishes a long-lived connection between your app and Slack's backend. This means that even when no communication between Slack and your app is active, the connection still remains established. This is inherently less reliable than HTTP, which only establishes a connection between your app and Slack at the moment that communication is needed (short-lived connection).

**Comment by abubakar364** [comment]
Noted! Thanks for the clarification

**Comment by abubakar364** [comment]
I have discussed this with one of Devops person and he suggest me that :

" Check the library you use to make websocket connection, it should has some configuration such as checking the connection before making calls, timeout and recreate the connection for a period of time. with those property configured properly, the issue will be gone. 
 
The reason for this error could be there is  timeout set up for the server side(Slack), it disconnects the connection after a period of time, but the client does not aware of it and handle it properly. "

is this the possible case ?

**Comment by seratch** [comment]
Regarding Socket Mode connections, this SDK handles the reconnection logic internally. The Socket Mode modules of this SDK have been utilized by many companies for several years, and we have never encountered this question before. Therefore, I suspect that this "remote reset" error might be unique to your environment.

One recommendation I have is to enable debug-level logging for your Bolt app and check the outputs when the issue occurs. Specifically, if the reconnection fails, there should be some error or warning messages describing the situation and its cause. You can configure the logging settings using the standard slf4j-api to enable the detailed logging.

Lastly, if your issue is related to WebSocket communications between your server and Slack, as Fil suggested, switching to Request URL endpoints might be a more immediate solution worth considering.

**Comment by seratch** [comment]
If you're interested in the implementation details, reading the following source code and its other internal modules would be the best way: 
- https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-client/src/main/java/com/slack/api/socket_mode/SocketModeClient.java
- https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-client/src/main/java/com/slack/api/socket_mode/impl/SocketModeClientTyrusImpl.java

In a nutshell, the Socket Mode client has an internal thread executor called sessionMonitorExecutor. This background thread monitors the connection health. If the current connection seems to be stale, the background thread tries reconnecting. For more details like intervals, please check the source code. Also, some settings are customizable if you want to do so.

Another approach is that, as I mentioned, enabling slf4j's debug-level logging and seeing the logging outputs when a connection is terminated. You can do manual testing just by disabling internet connection on your local machine.
