### ISSUE TITLE
Deployment guide documents

### ISSUE THREAD

**Issue by seratch** [slackapi/java-slack-sdk#348]
### Issue Type

- [ ] Bug
- [ ] Enhancement / Feature request
- [ ] Question
- [x] Documentation

### Description

After releasing the initial stable version, the team will be working on the documents on the appropriate ways to deploy Bolt (for Java) apps to production servers. The team hasn't decided what cloud infra should be covered in the documents yet but the following should be great options.

* Heroku
* Google Cloud Run
* AWS API Gateway/Lambda

### Requirements (place an `x` in each of the `[ ]`)

* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by flyinprogrammer** [comment]
So I'd love to see some guidance around using this sdk to build lambda slack bots. I have everything working, based on the current documentation (which I need to submit a PR for), but I'm currently suffering from cold-boot lambdas taking too long to ACK a messages from Slack, which results in retry deliveries, and then my bot processing the same message multiple times.

Similarly, I'm not sure how a warmup function would help this because as soon as the lambda has to scale, the cold-boot lambda is going to suffer from the same latency issues. but maybe I miss understand something.

Are there recommendations from Slack to address these issues? Is it possible to store the message id in memory to detect receiving the same message more than once? Could/should that get added as part of a middleware in the lambda/functional libraries?

**Comment by seratch** [comment]
@flyinprogrammer 
Thanks for writing in here!

Regarding pull requests to this issue, the document team is still planning but we may have deployment guides for Bolt Java in somewhere else. So, if you're interested in writing about it, your own blog or somewhere else may be a good place at this point. If we decide to have such contents under https://slack.dev/java-slack-sdk/ and you're interested in contributing to the pages, of course, we'll really appreciate it.

For recommended ways to run Bolt apps on AWS Lambda, the following repository is not a part of this repository but checking the example may be helpful for you. 

https://github.com/seratch/bolt-kotlin-on-aws-lambda

The project uses serverless framework just for convenience (I'm a bit too lazy to write CloudFormation JSON). However, bolt-aws-lambda doesn't require serverless framework at all.

The concerned parts in the repository are:
* [Internal lambda function periodically running to warm up all the functions](https://github.com/seratch/bolt-kotlin-on-aws-lambda/blob/f46b0ed25f1f006315d11b9a14fcad2114407a41/serverless.yml#L36-L40)
* [Implementation of warmup handler](https://github.com/seratch/bolt-kotlin-on-aws-lambda/blob/f46b0ed25f1f006315d11b9a14fcad2114407a41/src/main/kotlin/hello/aws/WarmupHandler.kt)

`App#start()` initializes components and services internally. SlackApiLambdaHandler's constructor [calls the method](https://github.com/slackapi/java-slack-sdk/blob/v1.0.6/bolt-aws-lambda/src/main/java/com/slack/api/bolt/aws_lambda/SlackApiLambdaHandler.java#L31). `App#initialize()` calls services' initializer functions [this way](https://github.com/slackapi/java-slack-sdk/blob/v1.0.6/bolt/src/main/java/com/slack/api/bolt/App.java#L415-L442). A good example is a service [initializing S3 access](https://github.com/slackapi/java-slack-sdk/blob/v1.0.6/bolt/src/main/java/com/slack/api/bolt/service/builtin/AmazonS3InstallationService.java#L34-L50) (as you may know, it takes a bit long for the first access). It's also possible to register your own initializers using [this method](https://github.com/slackapi/java-slack-sdk/blob/v1.0.6/bolt/src/main/java/com/slack/api/bolt/App.java#L410-L413
).

Having such an internal warmup handler should work for your use case. If you see issues with it in real situations, please let me know 🙏

**Comment by flyinprogrammer** [comment]
>If you see issues with it in real situations, please let me know

I'm not exactly sure if you want to have a discussion about how warmups work here, but here's my understanding of how this example warmup logic is going to work:

- Ping AWS Lambda every [5 minutes](https://github.com/seratch/bolt-kotlin-on-aws-lambda/blob/f46b0ed25f1f006315d11b9a14fcad2114407a41/serverless.yml#L40)
- This ensures 1 lambda is always running so long as the timeout on the lambda is > 5 minutes (note the default using SAM seems to be 20 seconds, so this example code already doesn't work for me, nothing that can't be fixed in a PR though :bow:  )

What happens when our app scales to requiring 2 lambdas?

Well the second lambda will take too long to boot, Slack servers will timeout, and then deliver the message multiple times, and our app will start making multiple replies.

Which begs the question, lambda code needs a way to keep track messages that it's already replied to, and that bookkeeping needs to work across all running lambdas because it's possible the re-delivery goes to lambdas 1, 2, or N.

---

In my mind the above scenario exists, or am I wrong/crazy/delusional?

**Comment by seratch** [comment]
Your understanding of the example is correct. For my small utility app's case (a tiny Slack app providing slash commands & modal interactions), warming up every a few minutes (3 min for my real app) works and booted lambda instances never expire in 20 seconds. But probably it depends.

>Well the second lambda will take too long to boot, Slack servers will timeout, and then deliver the message multiple times, and our app will start making multiple replies.

You may already know this but the best bet for the scenario would be their Provisioned Concurrency. https://aws.amazon.com/blogs/compute/new-for-aws-lambda-predictable-start-up-times-with-provisioned-concurrency/

I've designed bolt-aws-lambda to be as small as possible in terms of deployed package size. That said, I'm aware that the initialization takes longer than functions written in other languages. For `@initDuration`, it takes 3.5 seconds for me. Needless to say, this means it doesn't work properly without pre-initialization (provisioned concurrency or warming up).

>that bookkeeping needs to work across all running lambdas because it's possible the re-delivery goes to lambdas 1, 2, or N?

If your app is not able to avoid 3-second timeouts for an unacceptable number of requests, as you mentioned, the app may need to consider tracking all not-yet-replied messages in your datastore. Unfortunately, this project doesn't offer any solution for it at this point. 

Hope you'll find this helpful. Also, when you find rooms for improvements on this project side, please feel free to share your thoughts/feedback in another ticket.

**Comment by seratch** [comment]
As we already have a few examples as below, let us close this issue now. If you need other examples, feel free to create a new issue for the request!

* https://github.com/slackapi/bolt-examples-aws-re-invent-2020
* https://github.com/slackapi/java-slack-sdk/tree/main/bolt-google-cloud-functions-example/src/main/java/functions
