### ISSUE TITLE
RichTextBlock documentation is nowhere found

### ISSUE THREAD

**Issue by PulsarBlow** [slackapi/java-slack-sdk#541]
### Issue Type

- [ ] Bug
- [ ] Enhancement / Feature request
- [x] Question
- [x] Documentation

### Description

> RichTextBlock documentation is nowhere found

Hello there 👋 ,

I'm looking for any official documentation/reference about the [RichTextBlock](https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-model/src/main/java/com/slack/api/model/block/RichTextBlock.java) (and its related RichText elements) which seems to be used in quite few API places (eg EventAPI > Message).

The only available piece of information can be found in the Changelog note [What you see is what you get and more and less](https://api.slack.com/changelog/2019-09-what-they-see-is-what-you-get-and-more-and-less), has been posted almost one year ago.

Searching in the [whole API reference](https://api.slack.com/search?query=rich_text_section) doesn't return anything useful either.

I also searched all over the net, stackoverflow, etc.. couldn't find anything valuable.\
Even the [official Slack Node SDK](https://slack.dev/node-slack-sdk) seems to not implement it.

What is going on with this Block type ? 😨 

```json
"event": {
        "client_msg_id": "76f9a8d9-84f0-44cd-92e1-bcd343f82be5",
        "type": "message",
        "text": "Nothing much",
        "user": "XXXXX",
        "ts": "1597730456.000500",
        "team": "XXXX",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "RI/",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Nothing much"
                            }
                        ]
                    }
                ]
            }
        ],
        "thread_ts": "1597730431.000200",
        "parent_user_id": "XXXX",
        "channel": "G015SS2E0D9",
        "event_ts": "1597730456.000500",
        "channel_type": "group"
    },
```

### Requirements

* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
Hi @PulsarBlow , thanks for asking a question here!

As you checked already, https://api.slack.com/changelog/2019-09-what-they-see-is-what-you-get-and-more-and-less is the only available information in the API site. 

The `rich-text` blocks are populated by Slack's WYSIWYG editor, and those blocks are supposed to be used by client apps for the editor feature.  As the 1st party apps also use our open APIs, those blocks are included in the API responses. However, this doesn't mean the Slack API Platform requires developers to deeply understand the blocks and utilize them.

>The text field will continue to contain a textual and markup-laden representation of the user's typed message.

As mentioned in the document this way, we recommend using the `text` field to access the message data. The field has the whole message in Slack's text format.

The Java SDK has been supporting the complete set of static types for all blocks/block elements. That's why this SDK has the types for those blocks and their elements. Other SDKs don't have types as they use more dynamic data models (e.g., JavaScript objects, dictionaries in Python).

If you have feedback on the `rich_text` supports in this SDK, please feel free to let us know by opening issues. We will promptly support missing ones if they exist.

**Comment by PulsarBlow** [comment]
Hello @seratch ,

Thank you for you answer !
Explained that way it makes a lot more sense.
