### ISSUE TITLE
How to respond to a specific chat message?

### ISSUE THREAD

**Issue by IlyasPatel** [slackapi/java-slack-sdk#670]
Is there a Java code example on how to respond to a specific message? I would like to perform some server-side checks and respond to a particular message with an emoji (The original message may have been created 5-10 minutes earlier?

**Comment by aoberoi** [comment]
Hi @IlyasPatel,

I think [this example](https://github.com/slackapi/java-slack-sdk/blob/v1.5.2/bolt-servlet/src/test/java/samples/EventsSample_WatchingYou.java) will get you most of the way there.

In that example, the app is listening for events of type [`"message"` from the Events API](https://api.slack.com/events/message). Note, when setting up the subscription in your app's configuration, you actually need to [subscribe to a specific kind of `"message"` event](https://api.slack.com/events/message#message-event-type__stars-pins-and-reactions__message-events-in-the-events-api), such as `"message.channels"`.

Let's assume your app is subscribed to `"message.channels"`, and your app's bot user is in some channel. Now for each message sent by any user in that channel, the event handler will run. This is where you'd perform your server-side checks to pick whichever particular message you'd like the app to react to. In the example, the event handler reacts to every message.

Your last statement is interesting. If your app is subscribed to an event and does not handle it, Slack will automatically retry sending your app that event first immediately, then again after 1 minute, then again after 5 minutes. If your app is always up (or even only briefly down), you can handle these events in nearly real time. However, if you're writing an app that is more like a one-off script, set to run on a schedule, that's quite different. In this script-like scenario, I'd recommend [using the API Client directly to call a method](https://slack.dev/java-slack-sdk/guides/web-api-basics#call-a-method). Specifically, you'd call [`conversations.history`](https://api.slack.com/methods/conversations.history) in order to fetch a part of the recent message history within a given conversation (channel, private channel, DM, or group DM). Once you've retrieved those messages, you could process them and react to them exactly as you would in the event handler described above. Before going down this route, I'd strongly recommend trying to build your app as a service that remains up, listening for events.

**Comment by seratch** [comment]
👋 Let us know if you need further help here. I will close this issue after waiting for your response for a few more days.

**Comment by IlyasPatel** [comment]
Would it be possible to use the _response_url_ in the same scenario?

The idea is to have an application always running which will call various external APIs based on a messages from Slack. These messages can be quite fast but the external services may be slow. Once the checks have been completed, I would like to update a specific message in Slack with a green tick mark emoji.

I like the idea of calling `conversations.history` so will investigate this aswell.

**Comment by seratch** [comment]
@IlyasPatel 

>Would it be possible to use the response_url in the same scenario?

No, it wouldn't. response_url is not available for any Events API handlers.
