### ISSUE TITLE
SocketMode app. Sometimes events are not delivered via web socket connections

### ISSUE THREAD

**Issue by BootGenius** [slackapi/java-slack-sdk#803]
Hi. I've implemented the socket mode app using the bolt-socket-mode library. Everything was working fine until today. For some reason, Slack started to not deliver some message events. When I start SockeModeApp everything is fine. There are no connection issues. When I type something in the channel sometimes a message event is delivered, sometimes it's not.  I can not figure out what is the problem. It seems that the problem can be on the Slack side. Some events are not delivered. If I send the message with the text "Hello world" it's delivered, when I send, for example, "123" it's not delivered. Can you please explain what can be the problem? Can it be that Slack itself does not deliver the message if all the scopes are set correctly and all the necessary events are selected on the Events page of the App?

**Comment by seratch** [comment]
Hi @BootGenius, thanks for asking the question!

>Can you please explain what can be the problem? Can it be that Slack itself does not deliver the message if all the scopes are set correctly and all the necessary events are selected on the Events page of the App?

If all the message deliveries of a specific type events stop, the situation can be due to the apps' configuration, the Slack server-side outage ([the status site](https://status.slack.com/) is available for checking ongoing incidents). But as you are intermittently observing the situation with the message events. Considering that, the possible causes I can think of are:

* You may have other processes connecting to Slack's Socket Mode servers. In this case, the Slack server-side can send payloads to active hosts in a round-robin manner. In this scenario, other processes (e.g., a process with an old version of your app running background, a deployed app that you've forgotten terminating) might be acknowledging some requests and do nothing in response.
  * In this case, you can try 1) creating a new app-level token and starting a new app instance with it 2) revoking the existing app-level token and terminating the old apps. If this resolves the issue, my hypothesis here is valid.
* If you observe the situation only with either a specific app or a specific workspace, something wrong on the Slack server-side may be happening only to those.
  * In this case, we would like you to contact our customer support agents (by using `/feedback` in your Slack workspace or from https://my.slack.com/help/requests/new). As this issue tracker is a public place, we are unable to help you out with more detailed information about your workspace/app.

As an SDK maintainer, other things I can suggest are 1) to check error level ones in your app logs, 2) to turn debug-level logging as much as possible. The detailed logs can help you figure out what's happening to your apps. If something wrong on this SDK side is found in the logs, please let us know with the log information. We'll improve it as quickly as possible.

I hope this was helpful to you!

**Comment by BootGenius** [comment]
Hi, @seratch. Thank you for pointing out possible solutions. Yes, you were right. We were having one more developer running the application with the Slack SocketMode app using the same app-level token. And as you wrote, Slack sends WebSocket events in a Round Robbin manner. After I regenerated the app-level token I started to get all the events. The issue can be closed.
Thanks
