### ISSUE TITLE
Slack bot availability verification & disable listener suggestion

### ISSUE THREAD

**Issue by mikewoe** [slackapi/java-slack-sdk#818]
I'm trying to find way to check that slack bot is running.

Doesn't found any point for this in doc, so i trying to check via baseUrl/slack/event [url_verification](https://api.slack.com/events/url_verification)

I'm send POST, with my token but have a response with error (401 Unathorized)
`{"error":"invalid request"}`

Is it possible to check availability of the app?

Another question about opportunity to disable listener event suggestion
```
---
[Suggestion] You can handle this type of event with the following listener function:

app.event(MessageChangedEvent.class, (payload, ctx) -> {
  return ctx.ack();
});
```

**Comment by seratch** [comment]
Hi @mikewoe, thanks for writing in!

Regarding the first question (app healthcheck), you can have your own healthcheck endpoint and send a request to the URL. The endpoint can check database connections, and whatever. Refer to [this example app code in tests](https://github.com/slackapi/java-slack-sdk/blob/v1.10.0/bolt-servlet/src/test/java/test_locally/servlet_test/EndpointTest.java#L33-L38) to learn easily add additional endpoints.

As for the second question, we are planning to add a new option to automatically acknowledge `Message***Event` since the next release: https://github.com/slackapi/java-slack-sdk/issues/769
 At this moment, your app needs to have listeners for the subtyped message events too. 

I hope this was helpful to you. Is everything clear now?

**Comment by mikewoe** [comment]
@seratch, thx for clear answer

I will try it
