### ISSUE TITLE
Socket closed exception

### ISSUE THREAD

**Issue by fu1212** [slackapi/java-slack-sdk#849]
Hello,

When you use socket mode to develop, I want to know whether the socket will automatically close if the SocketModeApp is started for a long time without operation? How long is the interval? 
What should I do if I want the Socket not to close itself as long as the project is not stopped on the server?

This is the log of socket exceptions.
<img width="581" alt="1632102908(1)" src="https://user-images.githubusercontent.com/58798121/134304848-88d8f9e0-55ec-4273-acfc-c8ea06080af8.png">

**Comment by seratch** [comment]
Hi @fu1212, thanks for sharing the stacktrace. 

>whether the socket will automatically close if the SocketModeApp is started for a long time without operation? How long is the interval?

The underlying WebSocket connections can be closed for several reasons. You may see some errors for connectivity issues due to some reasons such as network issues in the host and outage on the Slack server-side. But the expected behavior is that Socket Mode client should automatically reconnect to the Slack server. The Socket Mode client in this SDK runs background threads to monitor the healthiness of its WebSocket connections. As long as you enable auto-reconnect mode (it's enabled by default), the background thread tries to establish a new connection for you regardless of the cause of disconnection.

Thus, if you only found the error level logs and the app still continued receiving WS messages from Slack, that's an expected behavior. On the other hand, if your app stopped receiving while the host is connected to public internet, there may be a room for improvement on this SDK side.

I hope this answered your question here.

**Comment by fu1212** [comment]
yes, the background thread will establish a new connection. Thank you!
