### ISSUE TITLE
Radio buttons callback is never called on Andriod/iOS

### ISSUE THREAD

**Issue by amnsdh** [slackapi/java-slack-sdk#856]
Hi, everyone! 
Radio buttons callback is never called on Andriod/iOS.
It seems i am not the only one who faced the problem: https://stackoverflow.com/questions/68696216/callback-triggered-by-interactive-radio-button-not-working-in-android-ios-app-bu

#### The Slack SDK version

1.8.1

#### Java Runtime version

java version "14.0.1"

#### OS info

Windows 10

#### Steps to reproduce:

Send message with radio buttons, for example:

```json
{
  "blocks": [
    {
      "type": "input",
      "label": {
        "type": "plain_text",
        "text": "Do you like Slack?"
      },
      "element": {
        "type": "radio_buttons",
        "action_id": "pollAnswer",
        "options": [
          {
            "text": {
              "type": "plain_text",
              "text": "Yes"
            },
            "value": "{\"questionId\":\"104411d7-f332-4834-bef8-4b2baf346d5b\",\"index\":0,\"selected\":false}"
          },
          {
            "text": {
              "type": "plain_text",
              "text": "No"
            },
            "value": "{\"questionId\":\"104411d7-f332-4834-bef8-4b2baf346d5b\",\"index\":1,\"selected\":false}"
          },
          {
            "text": {
              "type": "plain_text",
              "text": "Maybe"
            },
            "value": "{\"questionId\":\"104411d7-f332-4834-bef8-4b2baf346d5b\",\"index\":2,\"selected\":false}"
          }
        ]
      },
      "optional": false
    }
  ]
}
```
#### Expected result:

Action is triggered when radio button pressed
```java
slackApp.blockAction("pollAnswer", (req, ctx) -> {
    processPollAnswer(ctx, req);
    return ctx.ack();
});
```

#### Actual result:

Action does get triggered on desktop Slack client, but on mobile clients nothing happens.

**Comment by misscoded** [comment]
Hi @amnsdh! In the code sample you've provided, if you also include `"dispatch_action": true` on the input block, you should see consistent behavior across both desktop and mobile. 

As you can see in the table [here](https://api.slack.com/reference/block-kit/blocks#input_fields), the default for `dispatch_action` is set to `false` (but, that being said, it's unclear if it working on desktop despite this is intentional behavior or not). Either way, we recommend always setting this flag to `true` when wanting to receive `block_action` payloads.

Hope that's useful. Let us know if this resolves the issue (and thank you for also linking out to the existing SO question)! 🙂

**Comment by amnsdh** [comment]
Setting `dispatch_action` to true resolved the problem. Thanks a lot!
