### ISSUE TITLE
What does "new session is open" mean in socket mode?

### ISSUE THREAD

**Issue by RachelDong** [slackapi/java-slack-sdk#860]
Hello,

I'm using socket mode to run my app on a server. When I check the log on the server, I found the folloing piece:
```
2021-09-29 13:49:13.733  INFO 7 --- [tReadThread-550] c.s.api.socket_mode.SocketModeClient     : onClose listener is called (code: 1000, reason: )
2021-09-29 13:49:14.133  INFO 7 --- [tReadThread-561] c.s.api.socket_mode.SocketModeClient     : onClose listener is called (code: -1, reason: )
2021-09-29 13:49:14.525  INFO 7 --- [tReadThread-563] c.s.api.socket_mode.SocketModeClient     : New session is open
2021-09-29 18:49:19.641  INFO 7 --- [tReadThread-563] c.s.api.socket_mode.SocketModeClient     : onClose listener is called (code: 1000, reason: )
2021-09-29 18:49:20.317  INFO 7 --- [tReadThread-804] c.s.api.socket_mode.SocketModeClient     : onClose listener is called (code: -1, reason: )
2021-09-29 18:49:20.527  INFO 7 --- [tReadThread-806] c.s.api.socket_mode.SocketModeClient     : onClose listener is called (code: -1, reason: )
2021-09-29 18:49:20.739  INFO 7 --- [tReadThread-808] c.s.api.socket_mode.SocketModeClient     : New session is open
```
I wonder why socketmodeclient repeatedly opens new sessions and closes them? What does "New session is open" mean? Thanks in advance!

**Comment by seratch** [comment]
Hi @RachelDong, thanks for writing in!

Every a few hours, your Socket Mode client needs to establish a new connection with a new endpoint. That's why you see the new connection establishment this way. Please check the document for details: https://api.slack.com/apis/connections/socket-implement#disconnect

**Comment by RachelDong** [comment]
Hi @seratch , thanks for reply! Then does "onClose listener is called" mean the session is closed? For example, the following piece:
```
2021-09-29 13:49:14.525  INFO 7 --- [tReadThread-563] c.s.api.socket_mode.SocketModeClient     : New session is open
2021-09-29 18:49:19.641  INFO 7 --- [tReadThread-563] c.s.api.socket_mode.SocketModeClient     : onClose listener is called (code: 1000, reason: )
```
means that at time 13:49, a new connection is established, and 5 hours later, at 18:49, the connection is closed?

**Comment by seratch** [comment]
Yes, your understanding is correct!

**Comment by RachelDong** [comment]
Thanks a lot!

**Comment by seratch** [comment]
@RachelDong Before answering your questions, could you share more details of your app? Which implementation of Socket Mode client do you use? Which version? It seems that the logs are not by the latest version. As we improved some parts of the Socket Mode clients recently, you may see a bit difference with the latest version.

**Comment by seratch** [comment]
Thanks. There may not be a big difference with the version.

> Which implementation of Socket Mode client do you use? 

I'm more curious about this. Are you using Java-WebSocket based one?

**Comment by RachelDong** [comment]
Hi @seratch , thank you very much for giving the answer, really helpful! I want to confirm that, if multiple new sessions are open (maybe some of the session connections are not healthy), it is still possible that some sessions are running simultaneously, thus it is possible that duplicated messages could be generated. Is my guess reasonable?

**Comment by RachelDong** [comment]
Hi @seratch , sorry that I have to reopen the question again, actually the whole story is that I found sometimes my app sent duplicated messages after one click on the button. Examining the log, I found sometimes it opened several sessions at the same time, and that might cause the app sent duplicated messages,  do you have any advice to overcome or aviod this situation?

**Comment by seratch** [comment]
@RachelDong 
Event when your app has multiple connections, the Slack server-side sends a request to only one of the connections. Considering the circumstances, I am guessing that your app may be receiving the same request due to retries. If your app does not do `ctx.ack()` within 3 seconds, the Slack server-side tries to send the same request to any of the active connections. 

Can you check if your app always responds to requests with 3 seconds?

If the listener needs more than 3 seconds to process a request, like I suggested [here](https://github.com/slackapi/java-slack-sdk/issues/646#issuecomment-744807766), you can consider using `app.executorService` to run time-consuming code in a different thread. If you have many Slack Web API calls in a listener, you can use `ctx.asyncClient()` instead.

I hope this helps.

**Comment by seratch** [comment]
Hey @Mike1212-12, your question is not related to the one here. Let me create a new one for you before answering.

**Comment by Mike1212-12** [comment]
OK, Thank you! @seratch

**Comment by RachelDong** [comment]
@seratch Thanks a lot!

**Comment by yehezkiell** [comment]
Hi @seratch I have similar question regarding handle disconnect.

Is there any listener in `bolt-socket-mode` that trigger info disconnection?  

because as I read  here [bolt-socket-mode](https://api.slack.com/apis/connections/socket-implement#connect) we need to handle by requesting another url with websocket.

example code that I want to achieve:
```

fun main() {

    val botToken = System.getenv("SLACK_BOT_TOKEN")
    val appToken = System.getenv("SLACK_APP_TOKEN")
    val appConfig = AppConfig.builder().singleTeamBotToken(botToken).build()
    val app = App(appConfig)

    //code here if disconnect call startServer(appToken, app)
    
    app.message("") { event, context ->
        requireNotNull(event)
        requireNotNull(context)
        //reply message code
        context.ack()
    }

    startServer(appToken, app)
}

private fun startServer(appToken: String, app: App) {
    BotLogger.logInfo("server starting...")
    SocketModeApp(appToken, app).start()
}
```

**Comment by seratch** [comment]
@yehezkiell As the SocketModeClient handles the pattern under the hood for you, you don't need to implement the logic on your own: https://github.com/slackapi/java-slack-sdk/blob/v1.20.1/slack-api-client/src/main/java/com/slack/api/socket_mode/SocketModeClient.java#L353-L357

**Comment by yehezkiell** [comment]
@seratch So we don't have to implement anything to handle disconnect by our own?
this code is enough right?

```
fun main() {

    val botToken = System.getenv("SLACK_BOT_TOKEN")
    val appToken = System.getenv("SLACK_APP_TOKEN")
    val appConfig = AppConfig.builder().singleTeamBotToken(botToken).build()
    val app = App(appConfig)

    //code here if disconnect call startServer(appToken, app)
    
    app.message("") { event, context ->
        requireNotNull(event)
        requireNotNull(context)
        //reply message code
        context.ack()
    }

    startServer(appToken, app)
}

private fun startServer(appToken: String, app: App) {
    BotLogger.logInfo("server starting...")
    SocketModeApp(appToken, app).start()
}
```

**Comment by seratch** [comment]
Yes, you are right.

**Comment by yehezkiell** [comment]
ok thanks for the asnwer! @seratch
