### ISSUE TITLE
bolt-aws-lambda missing aws-java-sdk-s3 dependency

### ISSUE THREAD

**Issue by andyRokit** [slackapi/java-slack-sdk#907]
`bolt-aws-lambda` requires `aws-java-sdk-s3` to function however it is not included in the pom.

Note:  It is marked as a `provided` dependency in `java-slack-sdk` (which makes sense as its optional), but as far as I'm aware it's always required when using `bolt-aws-lambda`, therefore should be `compile` scope.

**Comment by seratch** [comment]
Hi @andyRokit, thanks for writing in!

Not having the `aws-java-sdk-s3` dependency in compile scope is intentional. Running AWS Lambda functions does not require S3 storage. Some developers may want to use a Lambda function without S3 storage (say, using DynamoDB for storing data/state).

If you use S3 along with AWS Lambda, please add the S3 dependency in your pom.xml.

**Comment by andyRokit** [comment]
Of course! :man_facepalming:
That makes perfect sense - thanks for the quick feedback.
