### ISSUE TITLE
Reading messages from a private channel in Slack

### ISSUE THREAD

**Issue by Jenith2211** [slackapi/java-slack-sdk#924]
Is there any pre defined method in slack api to read messages from a private channel?

**Comment by seratch** [comment]
Hi @Jenith2211, thanks for writing in!

You can use [`conversations.history` API method](https://api.slack.com/methods/conversations.history) with [the `groups:history` scope](https://api.slack.com/scopes/groups:history) for the purpose 👋 

I hope this helps!

**Comment by seratch** [comment]
I forgot to mention the method in the Java SDK. You can use `MethodsClient#conversationsHistory()` with a private channel ID: https://oss.sonatype.org/service/local/repositories/releases/archive/com/slack/api/slack-api-client/1.18.0/slack-api-client-1.18.0-javadoc.jar/!/com/slack/api/methods/MethodsClient.html#conversationsHistory(com.slack.api.methods.request.conversations.ConversationsHistoryRequest)

Let us know if you need more help here 👋 Otherwise, would you mind closing this issue?

**Comment by seratch** [comment]
Let us close this issue but, if you have any follow ups, please feel free to write in!
