### ISSUE TITLE
Slack AppMention events do not get fired reliably

### ISSUE THREAD

**Issue by Gayathri92** [slackapi/java-slack-sdk#926]
I've added a slack app to my slack desktop. I also added an event handler in my java code to handle AppMention events.

These are the permissions/subscripts I gave to my slack app:

scopes:
    bot:
      - app_mentions:read
      - chat:write
      - chat:write.customize
      - im:history
      - im:read
      - im:write
      - chat:write.public
      - channels:read
      - channels:history
      - groups:history
settings:
  event_subscriptions:
    bot_events:
      - app_mention
      - message.im

When I mention my slack app with @bot_name message in a private channel that I added it to, expected behavior is that it would trigger an AppMention event. Instead it throws a warning as 

```
2022-02-01 18:40:54.041Z [socket-mode-message-processor-worker-61] WARN  com.slack.api.bolt.App:1107 - No BoltEventHandler registered for event: message
---
[Suggestion] You can handle this type of event with the following listener function:

app.event(MessageEvent.class, (payload, ctx) -> {
  return ctx.ack();
});
```

It sometimes triggers AppMention events too but not always.

#### The Slack SDK version

com.slack.api:bolt-socket-mode: 1.15.0

#### Java Runtime version

java version : 11.0.5

#### OS info

ProductName:	macOS
ProductVersion:	11.6

**Comment by srajiang** [comment]
Hey @Gayathri92 - Based on the fact that sometimes you get AppMention events and sometimes you don't makes me think that the issue might be in where you're sending that message with @mentions the app. 

Is the private channel where you are experiencing the issue a DM with the app itself? Per the documentation, you would receive a regular message event https://api.slack.com/events/app_mention. The relevant lines are: 

> Messages sent to your app in direct message conversations are not dispatched via app_mention, whether the app is explicitly mentioned or otherwise. Subscribe to message.im events to receive messages directed to your bot user in direct message conversations.

I notice in this case you do have the message.im event enabled, so to handle this you would need to add an app.event handler as the error message suggests.

**Comment by Gayathri92** [comment]
Hey @srajiang, thanks for the response. I mentioned my app in a private "channel". This should be different from sending a direct message to the slack app right ? Correct me if I'm wrong.

**Comment by srajiang** [comment]
Yes @Gayathri92 that's right. A private channel is different than the DM wit the bot itself, so it looks like you have covered your bases there. To summarize it looks like you have:

* A private channel where you have your bot included as a member
* Your AppMention event handling code _sometimes_ fires, and _sometimes_ you receive the above error, and this can be triggered by the exact same user action (sending a message in the private channel which @-mentions your app) 

If that's the case, that would be error server-side and not likely to be due to bolt. We can confirm this by looking at the even payloads coming from Slack. Can you try `gradle run -DslackLogLevel=debug` and share what it looks like when you receive the app mention event and what it looks like when you receive the message event?

**Comment by Gayathri92** [comment]
@srajiang Something interesting happened which I did not anticipate. So looks like my teammate and I were testing with the same slack app and the code which adds an event handler. Looks like both of our event handlers were listening to the same slack app's app mention event. Would it have been possible that events were being triggered but sent to his event handler and not mine? I remember reading that a slack app can have 10 active socket connections open. What is expected in this scenario?

**Comment by srajiang** [comment]
@Gayathri92 
>  Looks like both of our event handlers were listening to the same slack app's app mention event. 
At the moment, I'm a little unclear as to expected behavior for event payloads in that case. I will dig into this a little further.

In the meantime we strongly recommend for local development that each of you has your own separate development app. You can port your app's setup fairly straightforwardly by going to your app's configuration page -> App manifest -> and making a copy of the manifest. 

You can then create a new app using that manifest which your team can use which will contain the configurations you have already set up for your app.

**Comment by srajiang** [comment]
Hi @Gayathri92 - Looping back in here - I'm not finding any previous issues raised on Slack API side with AppMention vs. MessageEvent being fired inconsistently, so my best recommendation here is to give the modified local development setup I mentioned above a try and see whether that resolves your issue.

**Comment by yehezkiell** [comment]
I also facing this issue sometimes, so the problem is your slack bot app is listened by multiple client code right? @Gayathri92 cc @srajiang

**Comment by seratch** [comment]
@yehezkiell Yes, the most common cause of this situation is that there are some old processes or hosts that are still receiving requests for the same app but you might totally forget about the running processes (or those processes are unexpectedly still alive). Refer to my response at https://github.com/slackapi/java-slack-sdk/issues/803#issuecomment-895768180 for more details.
